// lib/constants.js

export const REGIONS = [
  { id: 'south-east', name: 'South East England', pop: 9300000 },
  { id: 'greater-london', name: 'Greater London', pop: 8800000 },
  { id: 'north-west', name: 'North West England', pop: 7400000 },
  { id: 'east-of-england', name: 'East of England', pop: 6300000 },
  { id: 'west-midlands', name: 'West Midlands', pop: 6000000 },
  { id: 'south-west', name: 'South West England', pop: 5700000 },
  { id: 'yorkshire', name: 'Yorkshire and the Humber', pop: 5500000 },
  { id: 'scotland', name: 'Scotland', pop: 5400000 },
  { id: 'east-midlands', name: 'East Midlands', pop: 4900000 },
  { id: 'wales', name: 'Wales', pop: 3100000 },
  { id: 'north-east', name: 'North East England', pop: 2700000 },
  { id: 'northern-ireland', name: 'Northern Ireland', pop: 1900000 }
];

// ... KEEP YOUR EXISTING export const MATCHES = [ ... ] DOWN HERE!

export const MATCHES = [
  // --- GROUP STAGE: MATCHDAY 1 (72 Matches) ---
  { id: 'm001', name: 'Match 1: Mexico vs South Africa (June 11)' },
  { id: 'm002', name: 'Match 2: Canada vs Japan (June 12)' },
  { id: 'm003', name: 'Match 3: Poland vs Egypt (June 12)' },
  { id: 'm004', name: 'Match 4: USA vs Colombia (June 12)' },
  { id: 'm005', name: 'Match 5: Switzerland vs South Korea (June 13)' },
  { id: 'm006', name: 'Match 6: Argentina vs Nigeria (June 13)' },
  { id: 'm007', name: 'Match 7: Sweden vs Australia (June 13)' },
  { id: 'm008', name: 'Match 8: Senegal vs Peru (June 13)' },
  { id: 'm009', name: 'Match 9: France vs Ivory Coast (June 14)' },
  { id: 'm010', name: 'Match 10: Serbia vs Iran (June 14)' },
  { id: 'm011', name: 'Match 11: England vs Chile (June 14)' },
  { id: 'm012', name: 'Match 12: Morocco vs Ukraine (June 14)' },
  { id: 'm013', name: 'Match 13: Spain vs Saudi Arabia (June 15)' },
  { id: 'm014', name: 'Match 14: Denmark vs Ecuador (June 15)' },
  { id: 'm015', name: 'Match 15: Brazil vs Wales (June 15)' },
  { id: 'm016', name: 'Match 16: Croatia vs Algeria (June 15)' },
  { id: 'm017', name: 'Match 17: Portugal vs Costa Rica (June 16)' },
  { id: 'm018', name: 'Match 18: Uruguay vs Scotland (June 16)' },
  { id: 'm019', name: 'Match 19: Germany vs Mali (June 16)' },
  { id: 'm020', name: 'Match 20: Hungary vs Tunisia (June 16)' },
  { id: 'm021', name: 'Match 21: Netherlands vs Jamaica (June 17)' },
  { id: 'm022', name: 'Match 22: Turkey vs Venezuela (June 17)' },
  { id: 'm023', name: 'Match 23: Italy vs Panama (June 17)' },
  { id: 'm024', name: 'Match 24: Austria vs Cameroon (June 17)' },

  // --- GROUP STAGE: MATCHDAY 2 ---
  { id: 'm025', name: 'Match 25: Egypt vs Mexico (June 18)' },
  { id: 'm026', name: 'Match 26: South Africa vs Poland (June 18)' },
  { id: 'm027', name: 'Match 27: South Korea vs Canada (June 18)' },
  { id: 'm028', name: 'Match 28: Japan vs Switzerland (June 18)' },
  { id: 'm029', name: 'Match 29: Australia vs Argentina (June 19)' },
  { id: 'm030', name: 'Match 30: Nigeria vs Sweden (June 19)' },
  { id: 'm031', name: 'Match 31: Peru vs USA (June 19)' },
  { id: 'm032', name: 'Match 32: Colombia vs Senegal (June 19)' },
  { id: 'm033', name: 'Match 33: Iran vs France (June 20)' },
  { id: 'm034', name: 'Match 34: Ivory Coast vs Serbia (June 20)' },
  { id: 'm035', name: 'Match 35: Ukraine vs England (June 20)' },
  { id: 'm036', name: 'Match 36: Chile vs Morocco (June 20)' },
  { id: 'm037', name: 'Match 37: Ecuador vs Spain (June 21)' },
  { id: 'm038', name: 'Match 38: Saudi Arabia vs Denmark (June 21)' },
  { id: 'm039', name: 'Match 39: Algeria vs Brazil (June 21)' },
  { id: 'm040', name: 'Match 40: Wales vs Croatia (June 21)' },
  { id: 'm041', name: 'Match 41: Scotland vs Portugal (June 22)' },
  { id: 'm042', name: 'Match 42: Costa Rica vs Uruguay (June 22)' },
  { id: 'm043', name: 'Match 43: Tunisia vs Germany (June 22)' },
  { id: 'm044', name: 'Match 44: Mali vs Hungary (June 22)' },
  { id: 'm045', name: 'Match 45: Venezuela vs Netherlands (June 23)' },
  { id: 'm046', name: 'Match 46: Jamaica vs Turkey (June 23)' },
  { id: 'm047', name: 'Match 47: Cameroon vs Italy (June 23)' },
  { id: 'm048', name: 'Match 48: Panama vs Austria (June 23)' },

  // --- GROUP STAGE: MATCHDAY 3 (FINAL GROUP GAMES) ---
  { id: 'm049', name: 'Match 49: Mexico vs Poland (June 24)' },
  { id: 'm050', name: 'Match 50: South Africa vs Egypt (June 24)' },
  { id: 'm051', name: 'Match 51: Canada vs Switzerland (June 24)' },
  { id: 'm052', name: 'Match 52: Japan vs South Korea (June 24)' },
  { id: 'm053', name: 'Match 53: Argentina vs Sweden (June 25)' },
  { id: 'm054', name: 'Match 54: Nigeria vs Australia (June 25)' },
  { id: 'm055', name: 'Match 55: USA vs Senegal (June 25)' },
  { id: 'm056', name: 'Match 56: Colombia vs Peru (June 25)' },
  { id: 'm057', name: 'Match 57: France vs Serbia (June 26)' },
  { id: 'm058', name: 'Match 58: Ivory Coast vs Iran (June 26)' },
  { id: 'm059', name: 'Match 59: England vs Morocco (June 26)' },
  { id: 'm060', name: 'Match 60: Chile vs Ukraine (June 26)' },
  { id: 'm061', name: 'Match 61: Spain vs Denmark (June 26)' },
  { id: 'm062', name: 'Match 62: Saudi Arabia vs Ecuador (June 26)' },
  { id: 'm063', name: 'Match 63: Brazil vs Croatia (June 26)' },
  { id: 'm064', name: 'Match 64: Wales vs Algeria (June 26)' },
  { id: 'm065', name: 'Match 65: Portugal vs Uruguay (June 27)' },
  { id: 'm066', name: 'Match 66: Costa Rica vs Scotland (June 27)' },
  { id: 'm067', name: 'Match 67: Germany vs Hungary (June 27)' },
  { id: 'm068', name: 'Match 68: Mali vs Tunisia (June 27)' },
  { id: 'm069', name: 'Match 69: Netherlands vs Turkey (June 27)' },
  { id: 'm070', name: 'Match 70: Jamaica vs Venezuela (June 27)' },
  { id: 'm071', name: 'Match 71: Italy vs Austria (June 27)' },
  { id: 'm072', name: 'Match 72: Panama vs Cameroon (June 27)' },

  // --- ROUND OF 32 (16 Matches with Official Placeholders) ---
  { id: 'm073', name: 'Match 73: Winner Group A vs 3rd Place Group C/F/G/H (June 28)' },
  { id: 'm074', name: 'Match 74: Runner-up Group A vs Runner-up Group B (June 29)' },
  { id: 'm075', name: 'Match 75: Winner Group B vs 3rd Place Group E/F/G/I (June 29)' },
  { id: 'm076', name: 'Match 76: Winner Group C vs 3rd Place Group A/B/D/E (June 29)' },
  { id: 'm077', name: 'Match 77: Winner Group F vs Runner-up Group C (June 30)' },
  { id: 'm078', name: 'Match 78: Winner Group E vs 3rd Place Group A/B/C/D (June 30)' },
  { id: 'm079', name: 'Match 79: Winner Group D vs 3rd Place Group B/C/E/F (June 30)' },
  { id: 'm080', name: 'Match 80: Winner Group G vs 3rd Place Group A/E/H/I (July 1)' },
  { id: 'm081', name: 'Match 81: Runner-up Group E vs Runner-up Group F (July 1)' },
  { id: 'm082', name: 'Match 82: Winner Group H vs 3rd Place Group J/K/L (July 1)' },
  { id: 'm083', name: 'Match 83: Winner Group I vs 3rd Place Group C/D/G/H (July 2)' },
  { id: 'm084', name: 'Match 84: Runner-up Group G vs Runner-up Group H (July 2)' },
  { id: 'm085', name: 'Match 85: Winner Group J vs Runner-up Group I (July 2)' },
  { id: 'm086', name: 'Match 86: Winner Group K vs 3rd Place Group D/E/I/J (July 3)' },
  { id: 'm087', name: 'Match 87: Runner-up Group J vs Runner-up Group K (July 3)' },
  { id: 'm088', name: 'Match 88: Winner Group L vs 3rd Place Group E/H/I/K (July 3)' },

  // --- ROUND OF 16 (8 Matches) ---
  { id: 'm089', name: 'Match 89: Winner Match 73 vs Winner Match 74 (July 4)' },
  { id: 'm090', name: 'Match 90: Winner Match 75 vs Winner Match 76 (July 4)' },
  { id: 'm091', name: 'Match 91: Winner Match 77 vs Winner Match 78 (July 5)' },
  { id: 'm092', name: 'Match 92: Winner Match 79 vs Winner Match 80 (July 5)' },
  { id: 'm093', name: 'Match 93: Winner Match 81 vs Winner Match 82 (July 6)' },
  { id: 'm094', name: 'Match 94: Winner Match 83 vs Winner Match 84 (July 6)' },
  { id: 'm095', name: 'Match 95: Winner Match 85 vs Winner Match 86 (July 7)' },
  { id: 'm096', name: 'Match 96: Winner Match 87 vs Winner Match 88 (July 7)' },

  // --- QUARTER-FINALS (4 Matches) ---
  { id: 'm097', name: 'Match 97: Winner Match 89 vs Winner Match 90 (July 9)' },
  { id: 'm098', name: 'Match 98: Winner Match 91 vs Winner Match 92 (July 9)' },
  { id: 'm099', name: 'Match 99: Winner Match 93 vs Winner Match 94 (July 10)' },
  { id: 'm100', name: 'Match 100: Winner Match 95 vs Winner Match 96 (July 10)' },

  // --- SEMI-FINALS (2 Matches) ---
  { id: 'm101', name: 'Match 101: Winner Match 97 vs Winner Match 98 (July 14)' },
  { id: 'm102', name: 'Match 102: Winner Match 99 vs Winner Match 100 (July 15)' },

  // --- THIRD PLACE & FINAL (2 Matches) ---
  { id: 'm103', name: 'Match 103: Third Place Play-off (July 18)' },
  { id: 'm104', name: 'Match 104: The World Cup Final (July 19)' }
];